### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by tobyjaffey** [gbin/DonglePi#3]
I like the look of DonglePi. Great idea, great execution.
But, to decide whether to use it projects, I need to know the license it's provided under.

Specifically:
What license(s) are the software released under?
What license(s) are the hardware released under?

In the project root there is a GPLv2 COPYING file, but README.md states:
"It is GPL for educational and personal use"

I'm afraid that GPL cannot be used in this way, commercialisation (provided that the right to copy is preserved) is explicitly allowed (http://www.gnu.org/licenses/gpl-faq.html#NoMilitary).

GPL does not apply well to hardware projects. You might consider an Open Hardware license instead. (http://www.ladyada.net/library/openhardware/license.html)

If you wish to prevent commercialisation of your project, a license like CC-BY-NC would be appropriate (http://creativecommons.org/licenses/by-nc/2.0/)

**Comment by gbin** [comment]
Thanks ! The CC looks like the thing we should aim for.

**Comment by gbin** [comment]
They have a v4 : http://creativecommons.org/licenses/by-nc/4.0/, did you link to the v2.0 for any particular reason ?

**Comment by tobyjaffey** [comment]
No, just lazy googling, v4 is more recent.

**Comment by gbin** [comment]
Fixed.
